import { Genre } from "../interfaces/book.interface";

export const sampleBooks = [
  {
    title: "The Theory of Everything",
    author: "Stephen Hawking",
    genre: Genre.SCIENCE,
    isbn: "9780553380163",
    description: "An overview of cosmology and black holes.",
    copies: 5,
    available: true,
  },
  {
    title: "1984",
    author: "George Orwell",
    genre: Genre.FICTION,
    isbn: "9780451524935",
    description: "A dystopian novel set in a totalitarian regime.",
    copies: 12,
    available: true,
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: Genre.NON_FICTION,
    isbn: "9780062316097",
    description: "A compelling narrative about human evolution.",
    copies: 8,
    available: true,
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    genre: Genre.SCIENCE,
    isbn: "9780553380162",
    description: "Landmark work exploring time, space, and black holes.",
    copies: 10,
    available: true,
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    genre: Genre.HISTORY,
    isbn: "9780553296983",
    description: "The powerful diary of Anne Frank during WWII.",
    copies: 6,
    available: true,
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    genre: Genre.BIOGRAPHY,
    isbn: "9781524763138",
    description: "The memoir of the former First Lady of the United States.",
    copies: 4,
    available: true,
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: Genre.FANTASY,
    isbn: "9780547928227",
    description: "A fantasy classic about Bilbo Baggins’ adventure.",
    copies: 7,
    available: true,
  },
  {
    title: "Educated",
    author: "Tara Westover",
    genre: Genre.BIOGRAPHY,
    isbn: "9780399590504",
    description: "A memoir about a girl who escapes her survivalist family.",
    copies: 5,
    available: true,
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: Genre.FICTION,
    isbn: "9780743273565",
    description: "A novel about the American dream and 1920s glamour.",
    copies: 10,
    available: true,
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    genre: Genre.SCIENCE,
    isbn: "9780199291151",
    description: "Introduction to evolutionary biology and gene-centered view.",
    copies: 6,
    available: true,
  },
  {
    title: "Man’s Search for Meaning",
    author: "Viktor E. Frankl",
    genre: Genre.NON_FICTION,
    isbn: "9780807014271",
    description: "Psychological exploration of life in Nazi death camps.",
    copies: 3,
    available: true,
  },
  {
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: Genre.FANTASY,
    isbn: "9780590353427",
    description: "The first adventure of the young wizard, Harry Potter.",
    copies: 9,
    available: true,
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: Genre.FICTION,
    isbn: "9780060935467",
    description: "A timeless novel on racial injustice in the Deep South.",
    copies: 11,
    available: true,
  },
  {
    title: "Brief Answers to the Big Questions",
    author: "Stephen Hawking",
    genre: Genre.SCIENCE,
    isbn: "9781984819192",
    description:
      "Hawking's final thoughts on the biggest questions of science.",
    copies: 7,
    available: true,
  },
  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    genre: Genre.BIOGRAPHY,
    isbn: "9780316548182",
    description: "Autobiography of one of the greatest leaders of our time.",
    copies: 5,
    available: true,
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    genre: Genre.HISTORY,
    isbn: "9781599869773",
    description: "Ancient military treatise with timeless strategies.",
    copies: 8,
    available: true,
  },
  {
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    genre: Genre.FANTASY,
    isbn: "9780066238500",
    description: "A classic fantasy series filled with magic and adventure.",
    copies: 4,
    available: true,
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    genre: Genre.HISTORY,
    isbn: "9780393317558",
    description:
      "Explains why civilizations developed differently around the world.",
    copies: 6,
    available: true,
  },
  {
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    genre: Genre.NON_FICTION,
    isbn: "9781400052189",
    description: "The story of a woman whose cells changed medical research.",
    copies: 7,
    available: true,
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: Genre.FICTION,
    isbn: "9780061122415",
    description: "A novel about a boy pursuing his personal legend.",
    copies: 10,
    available: true,
  },
];
